### ISSUE TITLE
media path import issue?

### ISSUE THREAD

**Issue by Call-Me-Dave** [VaZaR00/FTB-gramps-import-addon#3]
Using the ftb sample file and attempting to look at a media file after using the addon and **setting the gramps media folder to "c:\\documents\myheritage\photos\"**  shows the following error:

> Warning: History: Exception occurred in callback function.
> Traceback (most recent call last):
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\gen\utils\callback.py", line 424, in emit
>     fn(*args)
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\gen\plug\_gramplet.py", line 303, in update
>     self.update_has_data()
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\gramplet\metadataviewer.py", line 74, in update_has_data
>     self.set_has_data(self.get_has_data(active))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\gramplet\metadataviewer.py", line 86, in get_has_data
>     return self.view.get_has_data(full_path)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\lib\libmetadata.py", line 313, in get_has_data
>     with open(image_path, "rb") as fd:
>          ^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'c:\\documents\\myheritage\\photos\\'

But clicking of the media file and right clicking to "Open Containing Folder" shows the correct folder!

looking at the Gramps media properties for one of the media entries shows the path is blank.

**Comment by VaZaR00** [comment]
Should be fixed now

**Comment by ghost** [comment]
sorry [latest update](https://github.com/VaZaR00/FTB-gramps-import-addon/commit/3b436b014fbd78b88af75915890db5f3aa6f0782) shows almost the same error the file path in the error now has double back slash "\\" ...

> Warning: History: Exception occurred in callback function.
> Traceback (most recent call last):
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\gen\utils\callback.py", line 424, in emit
>     fn(*args)
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\gen\plug\_gramplet.py", line 303, in update
>     self.update_has_data()
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\gramplet\metadataviewer.py", line 74, in update_has_data
>     self.set_has_data(self.get_has_data(active))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\gramplet\metadataviewer.py", line 86, in get_has_data
>     return self.view.get_has_data(full_path)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\GrampsAIO64-5.2.3\gramps\plugins\lib\libmetadata.py", line 313, in get_has_data
>     with open(image_path, "rb") as fd:
>          ^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'c:\\documents\\myheritage\\photos\\'
>

**Comment by ghost** [comment]
Ok it looks you are attempted to fix the addon looking for the path, but this error came from Gramps itself after the import when you goto the "Media" list view category and select one of the media file 

![2024-11-30 11_11_59-kennedy - Media - Gramps](https://github.com/user-attachments/assets/cd6dc446-dc73-4f26-9f23-617450a21364)

notice after the import the media **"Path:"** is empty for the import.

confirming I did reimport the sample file using the latest fixes you provided

**Comment by VaZaR00** [comment]
I get it. The media files i import from FTB arent moved anywhere on your computer, my addon sets their path as it is in FTB project. Okay i'll try fixing it with making copies of media files into gramps media folder.

**Comment by ghost** [comment]
> Okay i'll try fixing it with making copies of media files into gramps media folder.

Not sure that is the right thing to do as the files already exist at the location of the gramps media folder already.

my first comment mentions the location I set.

**Comment by ghost** [comment]
I believe the issue seems to be that when your addon imports the media file is also needs to add the filename as shown in the example.gramps example here  notice the "Path:" field has the file name so that when double clicked or used by gramps the complete path is completed with the filename shown , whereas addons imported does not have that filename with file extension  also the media title is empty usually it is the filename without the extension?

![2024-11-30 11_27_46-Example Family Tree - Media - Gramps](https://github.com/user-attachments/assets/3dceb47a-6346-4e42-835c-dcb76f239553)

**Comment by VaZaR00** [comment]
well, its very strange. Can you send project you trying to import and getting this bug? Because on my tests it works well, it gets the type and sets the path, it might some problems in FTB db. if you try just creating new tree in FTB and manually set photos it works well

**Comment by wroldwiedbwe** [comment]
> I was going to continue to document this but this is as far as I can go as I don't want an account with this company ([based on past interactions!](https://www.reddit.com/r/Genealogy/comments/xz0lkh/why_does_everybody_hate_myheritage_so_much/)) Hopefully some body else will continue! Will use the sample ftb file ( 95 person tree for American president John Fitzgerald Kennedy.))
> https://github.com/VaZaR00/FTB-gramps-import-addon/issues/2#issuecomment-2508673340

Looks like @Call-Me-Dave is using the sample ftb file ( located C:\Program Files (x86)\MyHeritage\Data\Sample\Database ) and has only installed and not logged into the program itself?  The photos @Call-Me-Dave 's screenshot seem to be copied from ( C:\Program Files (x86)\MyHeritage\Data\Sample\Photos ) 

So the main setup difference between yourself and @Call-Me-Dave is only one of you is logged into the ftb program!

Haven't tried it but I wonder what would happen if somebody with ftb send only the database and photos and the other person only had Gramps and attempted to import using your addon, would they get the error mentioned here?  Maybe set up a Win 10 VM with portable gramps and your addon and test?  Sorry I'd do it but it will be a few days.

**Comment by VaZaR00** [comment]
Yeah, when i tried importing Sample i had some issues with photos too, as some of them were empty, and they had strange connections, or hadn't at all. But i didn't catch this bug to pop up. Well i consider this issue is on ftb db side, because all the times i tested with my mock tree, media was importing without problems. So i need to have closer look at ftb database in each case to determine why bug occurs. 
P.s. and by some reason i cant open the Sample tree in FTB, it throws error...

**Comment by PQYPLZXHGF** [comment]
> tested with my mock tree, media was importing without problems

Can you make it available for other to test with also by providing it in a sample folder with the addon?

>  P.s. and by some reason i cant open the Sample tree in FTB, it throws error...

Have you report this to FTB developers, maybe the error for @Call-Me-Dave is a red herring because the Sample tree is corrupt in the first place?

**Comment by ghost** [comment]
> Looks like @Call-Me-Dave is using the sample ftb file ( located C:\Program Files (x86)\MyHeritage\Data\Sample\Database ) and has only installed and not logged into the program itself? The photos @Call-Me-Dave 's screenshot seem to be copied from ( C:\Program Files (x86)\MyHeritage\Data\Sample\Photos )

Yes, those are the files I mentioned I am using and confirming I have not logged into the program which is quite a ridiculous thing to need to do!

Is this issue valid or should your importer addon be able to detect if the ftb sqlite file is corrupted as seems to be suggested here?  

Can you proved a test ftb sqlite file with the addon as mentioned above, so I can test please?

**Comment by VaZaR00** [comment]
Just make your test tree, make few families with persons filled only with name, and make one person and fill there some fields and add few photos (its not hard). I cant send my own test trees because i deleted them, they were just small mock data for test. And i continue developing this addon, and will try to figure what is that problem exactly. But can you @Call-Me-Dave send me exact project (your local copy) where error occured, and were there problem only with photos? And were there all photos corrupted?

**Comment by ghost** [comment]
> Just make your test tree, make few families with persons filled only with name, and make one person and fill there some fields and add few photos (its not hard).

Not about it being hard, it is as I mentioned above about having zero interest in creating an account login!

I can only repeat that the files you want that I used already come with the FTB program and to recreate my issue you need to not be logged in.

My view is this addon should be able to import ( an later on write to) the ftb datafile  especially on a operating system that would never have the ftb installed.

Thank you for your efforts anyway.
